### ISSUE TITLE
Allow whitelisting specific page elements

### ISSUE THREAD

**Issue by chaorace** [Midnight-Lizard/Midnight-Lizard#142]
Midnight lizard currently conflicts somewhat with the SurfingKeys vi-like extension. Specifically, the 'visual mode' selection cursor gets inverted and becomes nearly impossible to see. (see below)
![](https://i.imgur.com/fnMO9Mng.png)

I think the best solution for issues like these is to allow whitelisting of certain page elements from color processing, preferably using a CSS-type selector.

**Comment by pavel-agarkov** [comment]
You can use custom property `--ml-ignore:true;` to ignore whatever is necessary.
In case of SurfingKeys it might be:
```css
.surfingkeys_cursor {
    --ml-ignore:true; // important to be without whitespace
}
```
There are many ways how to inject custom styles into your browser.
For example you can use stylish extension.
