### ISSUE TITLE
web form

### ISSUE THREAD

**Issue by gct-faisal** [Midnight-Lizard/Midnight-Lizard#234]

**Comment by gct-faisal** [comment]
As a user of midnight lizard I would like the ability for it to change the deafult black/dark text color used for input in web form fields so that input text becomes more legible in dark themes using dark background colors in web input forms.

**Comment by pavel-agarkov** [comment]
In most cases inputs will be processed accordingly to the selected color scheme.
If it does not work on some website please try to change processing mode to Filter or Simplified:
![image](https://user-images.githubusercontent.com/24639631/57883933-41403100-7830-11e9-97d6-c3f7b0e4e84d.png)
Let me know if it helped.

**Comment by gct-faisal** [comment]
Hey thanks for providing this opportunity to resolve the concern - here's what [the result](https://www.screencast.com/t/DYlzAr17xe2) looks like
I'm going to guess it's something unique to the site because this isn't largely an issue on other site forms.   I was hoping to figure out how to override the DOM entries in some custom field perhaps on a per site basis.

**Comment by pavel-agarkov** [comment]
Sure, if you have some experiences with CSS it is completely possible.
There are extensions that allow to override website's styles.
For example Stylus and GreaseMonkey. Those extensions can inject custom style sheets on per-website basis.
Basically you need to create a new style sheet, copy input field selector from DevTools and add rule like this:
```css
.your-input-field-selector {
    --ml-ignore:true;
    color: var(--ml-text-color) !important;
    background-color: var(--ml-main-alt-background-color) !important;
}
```
