### ISSUE TITLE
uBlock Origin Zap/Element Picker Overlays Frozen

### ISSUE THREAD

**Issue by jamesap-max** [Midnight-Lizard/Midnight-Lizard#245]
Browser: Firefox version 71.0 (64-bit)
Midnight Lizard version: 10.4.2
uBlockOrigin version: 1.24.2

Midnight Lizard interferes with the Zap and Element Picker functionality of uBlock Origin. Either of these functions creates a dynamic overlay in an iframe that allows you to pick a single element to remove or block.

However, when Midnight Lizard is active and Zap or Element Picker is triggered, the overlay freezes up and will not allow element selection. From examining the issue in Developer Tools, it seems to be caused by an **<svg id="midnight-lizard-filters" style="height: 0px; width: 0px; position: absolute;">** within the uBlock overlay iframe.

If I go into Developer Tools and either
- edit the HTML to delete **html#ublock0-epicker svg#midnight-lizard-filters**, or
- edit the CSS of **#ublock0-epicker svg** to remove the "top" attribute,

the overlay unfreezes and works OK until next time - but these are highly inconvenient workarounds.

Is it possible to fix midnight-lizard-filters so it no longer interferes with ublock0-epicker?

**Comment by pavel-agarkov** [comment]
The following CSS block will fix the problem:
```css
html#ublock0-epicker {
  --ml-ignore:true;
  filter: var(--ml-text-filter)!important;
}

html#ublock0-epicker>#midnight-lizard-filters {
  height: 0px!important;
  width: 0px!important;
  position: absolute!important;
}
```
You can apply it by using some other extension that allows to inject user styles.
Or you can wait for the next Midnight Lizard release.
